### ISSUE TITLE
CSRF token not set properly for production grunt build

### ISSUE THREAD

**Issue by flibbertigibbet** [WorldBank-Transport/DRIVER#110]
Attempting to save a record on vagrant-hosted port 7000 returns 403 with error:
```
CSRF Failed: CSRF token missing or incorrect.
```

Saving records works when hosting via grunt on port 7002.

**Comment by flibbertigibbet** [comment]
Seems to work in production.

**Comment by flibbertigibbet** [comment]
Also happens with schema editor on port 7000.

**Comment by sharph** [comment]
Hmm, two django apps on the same port could cause conflict
