### ISSUE TITLE
map page styling

### ISSUE THREAD

**Issue by flibbertigibbet** [WorldBank-Transport/DRIVER#111]
* Fit map to page (do not scroll vertically)
* Remove bar of white space below header
* Set z-index of header and header dropdowns to show over map controls
* Fix layer switcher styling (grey background)

**Comment by kshepard** [comment]
Looks like the majority of these have been implemented.

**Comment by flibbertigibbet** [comment]
The vertical scroll has been removed, but there's still issues with fitting the header, the header content still goes behind the map (z-index issue), and the layer switcher needs styling fixes.

**Comment by mtedeschi** [comment]
Some of this is related to the markup being used (see issue #158 for more information). I styled the layer switcher for now, but leaving this open till that is resolved so I can make sure this is all actually fixed.
