### ISSUE TITLE
Record details view does not scroll

### ISSUE THREAD

**Issue by flibbertigibbet** [WorldBank-Transport/DRIVER#121]
If content is taller than the screen, browser should scroll vertically; instead, content is cut off at bottom of screen.

![image](https://cloud.githubusercontent.com/assets/960264/9742314/57c1afcc-562d-11e5-826a-4bdadbe3d127.png)

**Comment by kshepard** [comment]
This was working this morning: it's probably due to some styling changes in: #114.

**Comment by flibbertigibbet** [comment]
Probably [here](https://github.com/WorldBank-Transport/DRIVER/blob/develop/web/app/styles/partials/_record-list.scss#L2).

**Comment by flibbertigibbet** [comment]
Fixed in #124.
