### ISSUE TITLE
Record type selector on map page has no option to show all

### ISSUE THREAD

**Issue by flibbertigibbet** [WorldBank-Transport/DRIVER#136]
Once a record type is selected, there's no way to unselect it to show all types again.

**Comment by kshepard** [comment]
@jbranigan can weigh in here, but I don't think we'll want an option to show all all record types at once -- viewing a single record type at a time should be sufficient.

**Comment by jbranigan** [comment]
I can imagine folks wanting to see accident locations and interventions at the same time. If this isn't blocking other work, we can come back to this in the next sprint.
