### ISSUE TITLE
Styling support for dashboard widgets

### ISSUE THREAD

**Issue by jbranigan** [WorldBank-Transport/DRIVER#206]
They are relying on width, mainly, so sometimes the height doesn't look right.

**Comment by mtedeschi** [comment]
I styled up the rest of the widgets, but having trouble with the TODDOW. It seems like we need some more math in here to constrain to the width of the block, but also check the height to confirm it doesn't expand past the bottom edge (realistically 10px in that block so it's nicely padded).

<img width="799" alt="screen shot 2015-10-25 at 2 21 21 pm" src="https://cloud.githubusercontent.com/assets/842387/10717095/82ca01bc-7b24-11e5-836b-86846903ef1e.png">
