### ISSUE TITLE
Filter name updates to include selections

### ISSUE THREAD

**Issue by jbranigan** [WorldBank-Transport/DRIVER#220]
This will quickly break the layout. Let's just keep the name of the filter, and append a class to it so that we can style it slightly differently if something's actively selected.

**Comment by kshepard** [comment]
Looked into this a little bit since I thought it would be super easy. That behavior is built-in to the bootstrap-select control and may take a decent amount of effort in order to rip out.

**Comment by jbranigan** [comment]
Might be easier... https://github.com/silviomoreto/bootstrap-select/issues/1059

**Comment by kshepard** [comment]
Nice find, I'll take a look into that.
