### ISSUE TITLE
Style map popups

### ISSUE THREAD

**Issue by mtedeschi** [WorldBank-Transport/DRIVER#230]
Map popups need some love.

**Comment by kshepard** [comment]
I think we should re-use the directive for displaying details here. Probably just without the mini-map.

**Comment by mtedeschi** [comment]
This might be related to what @kshepard said above, but the content needs some rethinking. I've attached what was in the wireframes...

<img width="487" alt="screen shot 2015-10-30 at 12 44 04 am" src="https://cloud.githubusercontent.com/assets/842387/10838629/79216b4a-7e9f-11e5-863a-b27909f31675.png">

![2015_06_24_worldbank_wireframes-web_v03_map-q](https://cloud.githubusercontent.com/assets/842387/10838641/8ff6921e-7e9f-11e5-84d2-447023fa191c.jpg)

**Comment by mtedeschi** [comment]
Via @jbranigan: Date when it occurred, and then link. Optionally, anything that's marked as filterable (like severity, vehicle type(s), collision type).

**Comment by jbranigan** [comment]
We might be able to pull some styling / development work from these popups: http://visualization.phillybuildingbenchmarking.com/#/map

**Comment by mtedeschi** [comment]
@jbranigan @kshepard, I styled these up and added in the markup like we discussed, but need some help getting the proper routing in for linking to the record's details and edit views.
