### ISSUE TITLE
Improve hovering on stepwise graph

### ISSUE THREAD

**Issue by kshepard** [WorldBank-Transport/DRIVER#238]
Hovering over a point is a little glitchy: the popup seems to disappear when the cursor is over a piece of the line. I think the points need to be drawn after the line (or increase the z-index of the points).

**Comment by flibbertigibbet** [comment]
This used to also be the case for the TODDOW, though that seems to have improved; tooltip logic was taken from there.

**Comment by kshepard** [comment]
ToDDoW does seem a little glitchy too, probably both should be investigated.
