### ISSUE TITLE
Subregion picker sometimes blank

### ISSUE THREAD

**Issue by flibbertigibbet** [WorldBank-Transport/DRIVER#256]
On selecting my top-level region, the sub-region picker shows no selections, and the dropdown contents are blank. On switching to my second-level region, however, the sub-region picker populates appropriately and shows the last selection.

**Comment by kshepard** [comment]
So you have multiple boundary shapefiles loaded, but only one of them is listing the polygons when selected? I wonder if there may be a problem with that first shapefile (or maybe the attribute you chose as the label was empty?).

**Comment by flibbertigibbet** [comment]
It was working before I updated my develop branch.
