### ISSUE TITLE
Data entry comments

### ISSUE THREAD

**Issue by jbranigan** [WorldBank-Transport/DRIVER#294]
- [ ] Time picker should default to now. I know we still have some work to do on the time picker, but just now it took me > 30s to enter the date and time. Second time to about 5 seconds :)
- [ ] Turn off scroll-to-zoom
- [ ] Check for double-click on map?
- [x] It's easy to lose track of multiple people while entering - maybe need @mtedeschi to try entering a few.
- [x] Might be worth sticking the save / cancel buttons to the bottom of the viewport...

**Comment by mtedeschi** [comment]
In the latest, I made some big styling changes to try to improve things. It would be great to have these be collapsed by default (Accident Details, Persons, Vehicles) to make the view less scary.

<img width="1161" alt="screen shot 2015-12-01 at 3 26 46 pm" src="https://cloud.githubusercontent.com/assets/842387/11513253/1557130c-9840-11e5-9dda-591b3361a490.png">
<img width="858" alt="screen shot 2015-12-01 at 3 26 57 pm" src="https://cloud.githubusercontent.com/assets/842387/11513260/1a0a0710-9840-11e5-976d-4cc0cda13491.png">

**Comment by kshepard** [comment]
Nice. I think it's pretty simple to start them as collapsed, with a parameter to json-editor. We can try that out. If you're done with making changes to that branch, would you be able to submit a PR?
