### ISSUE TITLE
Add edit button to accident detail view

### ISSUE THREAD

**Issue by jbranigan** [WorldBank-Transport/DRIVER#295]
I was viewing an accident, and wanted to make a quick edit. I'm sure this will be a common scenario.

**Comment by mtedeschi** [comment]
If you want to add this in, I can double-check on styling. If you'd like placement advice, just let me know.

**Comment by jbranigan** [comment]
@mtedeschi one of the problems we're having with this is the UX. We can't just edit inline because some of the forms are super long and really don't belong in a modal. I think where we are at this point is opening the edit form in a new tab.
