### ISSUE TITLE
Logging in to the editor (even as admin) doesn't seem to work

### ISSUE THREAD

**Issue by ddohler** [WorldBank-Transport/DRIVER#348]
If am logged out and try to log in via the Schema Editor login page using administrator credentials, I get a message saying "Must be an administrator to access this portion of the site". However, if I log in via the viewer login page and then subsequently visit the the Schema Editor, I'm able to access it normally.

**Comment by flibbertigibbet** [comment]
@kshepard and I discussed this. If the editor were on a separate path that is not a child of the front-end site, then cookie paths would work as they're supposed to and this would not be an issue; the logins would be separate. However, it's unclear if we will be able to easily set up subdomains in the production environment.

As it is, the permissions on the back end will result in errors if a non-admin user tries to do things in the schema editor.

**Comment by flibbertigibbet** [comment]
Oh, I see what you mean; administrators cannot log in to the editor, and are told they don't have administrator access. (What I mentioned above should probably be a separate issue.)

**Comment by ddohler** [comment]
Oh yeah, sorry, that's what I meant. Updated the title to make that clearer.
