### ISSUE TITLE
Filters fail to appear on first load

### ISSUE THREAD

**Issue by kshepard** [WorldBank-Transport/DRIVER#394]
When loading the dashboard or map page directly, there is a javascript error in the console:
`TypeError: Cannot read property 'uuid' of undefined`

This causes the filters to not be visible. It appears that loading the list page directly doesn't exhibit this error.

**Comment by KlaasH** [comment]
f8d7ada fixed an error like that, but I'm still seeing the filters to fail to load initially.

**Comment by kshepard** [comment]
This appears to be fixed.
