### ISSUE TITLE
SA - "Save" / "Cancel" Button on Edit Incident Unresponsive

### ISSUE THREAD

**Issue by tgilcrest** [WorldBank-Transport/DRIVER#541]
This only applies to the edit page that comes up when you first "view" an incident and then and use the "Edit" link on the incident details popup.  When edit is clicked, it opens a new tab to edit the incident.  Making a change and then saving or canceling don't make the change or close the new tab.  

This is different than just going straight to edit from the record list.  When the user goes that way, the it stays on the same tab and goes to the edit page.  Save / Cancel work for this workflow

**Comment by kshepard** [comment]
I can't reproduce the `Save` portion of this issue. Saving seems to work just fine. The `Cancel` button is unresponsive though, and I think when viewing the stand-alone page version, the `Cancel` button should not be displayed (or it could stay, but have it close the tab).
