### ISSUE TITLE
SA - Editing Related Content Type Creates Duplicates

### ISSUE THREAD

**Issue by tgilcrest** [WorldBank-Transport/DRIVER#543]
When trying to make some changes to a Related Content type, we saved the changes and then returned to the View Related Content.  In the list of related content, the type had been duplicated.  However, in the app, only one of the types of Related Content was still visible (for example, it didn't show two "Photos" tabs when viewing an incident).

When we deleted of the duplicate types, *some* of the tabs were also deleted in the app incident details.  From their appearance in the schema editor they are identical, so we couldn't tell which one was actually connected to the app (until you changed / deleted one). 

This also happened for Incident details, which was also duplicated. Because it is required, it can't be deleted.  This has also created duplicate filters in the record list.

**Comment by ddohler** [comment]
This is caused specifically by editing the Plural Title for the Related Content Type; this should be avoided until we've got a fix. Other edits should be fine.
