### ISSUE TITLE
SA - Record Type Name Change Caused App to Stop Functioning

### ISSUE THREAD

**Issue by tgilcrest** [WorldBank-Transport/DRIVER#546]
When we changed the name of the Record Type "Incident" to "Crash" as per feedback from Saudis, the incident list, dashboard and map to stop functioning.  The pages would not load their components that are found below the header bar.  Changing back to "Incident" seemed to fix this.  I did not yet attempt to reproduce this due to wanting it to work for the demo.

**Comment by ddohler** [comment]
This is expected behavior -- the front-end uses a pre-defined name of a RecordType in order to figure out which specific RecordType and RecordSchema to use; if we change the name of the RecordType then we need to update the front-end configuration to match.
