### ISSUE TITLE
SA - Error Exporting CSV

### ISSUE THREAD

**Issue by tgilcrest** [WorldBank-Transport/DRIVER#552]
Received this message while trying to use the Export CSV option:

![image](https://cloud.githubusercontent.com/assets/14098314/15526642/08da377c-223c-11e6-83fd-ad7e1af06270.png)

**Comment by tgilcrest** [comment]
May be related to #534

**Comment by ddohler** [comment]
This is fixed, it just hasn't been deployed yet. I'll leave this open until we deploy.

**Comment by kshepard** [comment]
Yes, exactly. I deployed the recent code to the web application server last night, but the celery server was too low on disk space and couldn't be deployed even after cleaning up docker images, so it'll probably require increasing the disk space first.

**Comment by kshepard** [comment]
Actually, it looks like this is a separate issue. The first fix properly encodes the column names, but this is failing on the name of the file. That will need to be encoded as well.
