### ISSUE TITLE
SA - Android App Not Respecting Schema Restrictions

### ISSUE THREAD

**Issue by tgilcrest** [WorldBank-Transport/DRIVER#562]
It seems like data type restrictions are not being respected by the android app.  For example, Number of Deaths is defined as a number in the schema editor.  However, I could enter 'gh' for that value and it would upload to the database.  When I checked that record in the record list, it had 'gh' as the value for that field.

The example record's Date & Time: 6/1/16 11:48 AM

**Comment by tgilcrest** [comment]
Also seems to be the case for Required fields.  The only required field it currently complains about being empty is the "Occurred" field, which isn't defined in the schema editor.

**Comment by flibbertigibbet** [comment]
Caused by #577.

The text-type number fields are also the required fields.
