### ISSUE TITLE
Plan AWS instance migration

### ISSUE THREAD

**Issue by rmartz** [WorldBank-Transport/DRIVER#739]
# Overview
The World Bank wants to migrate all of their demo instances to a different AWS account to help group DRIVER resources in their own scope.

The DRIVER application resides on EC2 instances that were made manually, and according to AWS documentation cannot be moved directly and will need to be recreated, either from an AMI created by the existing instances, by hand again, or using the existing CloudFormation template. The application code is contained within two Docker containers that are deployed via Ansible, and the application state is maintained by Postgres running directly on the EC2 instance.

The goal for this task is to determine what our plan is for moving these EC2 instances to a new application. We likely will also need to request the World Bank to provide us with administrative access to the new AWS account.

# Acceptance Criteria
- Meet with ops and decide on a plan for doing this
- Create any necessary tasks
- Get admin access from the World Bank

**Comment by jeancochrane** [comment]
Created #749 to track this work. We're cleared to have a day of downtime while we migrate the stacks. Currently blocked while we wait for credentials to the new account.
