### ISSUE TITLE
Crash data saving

### ISSUE THREAD

**Issue by AntoninoFRED** [WorldBank-Transport/DRIVER#791]
We have created with the "editor" a database structure to be used in Ivory Coast. It seems this structure is not automatically considered in the Web Application.

In the FAQ we found a similar problem:
- problem: "Why do I see the JavaScript error: Cannot read property 'uuid' of undefined?"
- issue: "This can happen if no Record Type exists with the name configured in: web_js_record_type_primary_label. Make sure to update that group_var accordingly."

Based on this we have changed the name of the "record type" using the default value used in the code (from "accident" to "crash").
However, the same problem still appears.

Can you please provide explanations on how using the structure for the database we have created in editor?
This is urgent since for the moment we are not able to store any data using the web application

**Comment by AntoninoFRED** [comment]
This issue has been solved by changing the name of the "record type" into "incident".

**Comment by rmartz** [comment]
That's good to hear that you were able to find a solution to the problem! I'm going to go ahead and close this issue since the problem has been solved.
