### ISSUE TITLE
Error not allowing to visualise the saved crashes

### ISSUE THREAD

**Issue by AntoninoFRED** [WorldBank-Transport/DRIVER#793]
The following error seems not allowing to visualise the saved crashes.
Can you please solve?
TypeError: Cannot read property 'schema' of undefined
    at f (scripts.js:4386)
    at a (scripts.js:4404)
    at Object.g [as invoke] (vendor.3474678b.js:4)
    at j.instance (vendor.3474678b.js:5)
    at n (vendor.3474678b.js:5)
    at vendor.3474678b.js:5
    at h (vendor.3474678b.js:6)
    at vendor.3474678b.js:6
    at o.$eval (vendor.3474678b.js:6)
    at o.$digest (vendor.3474678b.js:6)
(anonymous) @ vendor.3474678b.js:6

**Comment by rmartz** [comment]
Hi Antonino! What page did you see this error on? Does this happen on the Map and Dashboard pages (Possibly related to the problem you reported in #792), or somewhere else?

**Comment by AntoninoFRED** [comment]
Hi. Yes this happenned on the Map and Dashboard.
However, I just tried again to access to Driver and now I can see the crashes on map and on dashboard (even if I did nothing).
Do you know why this can happen?

**Comment by rmartz** [comment]
It's hard to say offhand, there are a variety of causes that could lead to the maps to failing to load. The maps are handled by a service called Windshaft, so if it happens again it may be useful to [check the Windshaft log file](https://github.com/WorldBank-Transport/DRIVER/blob/master/doc/logging.md#tile-server-windshaft) and see if there are any errors in there. Log files are only stored for a relatively short period of time, though, so errors from the original problem might not be there anymore.

**Comment by tgilcrest** [comment]
It sounds like this was resolved. If you see this again and have steps to reproduce the issue then we can investigate.
