### ISSUE TITLE
when French language will be released?

### ISSUE THREAD

**Issue by paolantoni** [WorldBank-Transport/DRIVER#798]
To deploy on production environment without doing manual changes i'm asking when you are planning to release the French language that is into the [development branch](web/app/i18n/fr.json)? 
The power of ansible, considering the production file requires for a TAG (to match the source code version with the docker container version) is to execute the playbooks .. but if to collect a great update (French 284.9 million total speakers) I have to mix the code from a tag with a branch... I'm asking why release cycle are not close to these big changes (in terms of user experience)..

**Comment by rmartz** [comment]
Hi Federico! We typically create release versions as necessary - I've placed a task on the schedule to create a release version for the French translations. We'll give an update here when it goes out!

**Comment by kshepard** [comment]
A release has been created (2.0.4), which includes the French translations.
