### ISSUE TITLE
Gradle fails to process messages correctly

### ISSUE THREAD

**Issue by kshepard** [WorldBank-Transport/DRIVER#804]
When Gradle starts up, it prints out the following log message, and then never seems to process messages related to rebuilding JAR files:
```
Setting up redis subscription for gradle task
Pinging Redis to test connectivity
Starting Redis subscription...
Listening for messages...
Received item
Item was not a message, it was a subscribe
```
This issue was potentially introduced in #765, which has an added block of logic for logging, but not processing, subscriptions, but will require further investigation to determine the exact cause.

**Comment by flibbertigibbet** [comment]
Building schema JARs with `driver-gradle` is working for me locally. The extra log message for `Item was not a message, it was a subscribe` is harmless.
