### ISSUE TITLE
misaligned map tiles

### ISSUE THREAD

**Issue by flibbertigibbet** [WorldBank-Transport/DRIVER#86]
The Leaflet map tiles do not always line up.

![image](https://cloud.githubusercontent.com/assets/960264/9524503/4f8830a8-4cad-11e5-87b0-a86c4cecc7ed.png)

**Comment by flibbertigibbet** [comment]
This seems to be specific to Stamen tiles (toner and toner-lite). Swapping out for CartoDB Positron in #87.

**Comment by jbranigan** [comment]
Nice. I'm liking Positron more than toner anyway these days.
